feat: update dependencies and pubspec.lock
verywellced/pokedex-async-redux pull request #5
Opened 2023-03-16 09:03 UTC by verywellced

feat update dependencies 
- update pubspec.lock
- delete .iml file

2023-03-16 09:25 UTC, nelbinffufm requested changes

2023-03-16 09:25 UTC, nelbinffufm commented on pubspec.yaml
> +
remove excess white space

2023-03-16 09:33 UTC, nelbinffufm approved these changes

2023-03-16 09:45 UTC, nelbinffufm approved these changes

2023-03-17 03:29 UTC, shawn-ffufm approved these changes

2023-03-17 03:29 UTC, merged